### PR TITLE
Rörelsemodul

### PR DESCRIPTION
**Pull request by fredrikhaggbom**
Added module "Rörelse" with subviews and admin views.

Note: Requires this branch of the app:  https://github.com/helsingborg-stad/app-laiban-ios/pull/22

Main flow:
https://user-images.githubusercontent.com/24652414/200827977-5ae9b83a-d5d9-4f9d-ba9d-06e58d73f117.mov

Admin:
https://user-images.githubusercontent.com/24652414/200828273-38db9acc-9c15-45e5-ade8-45f0373da486.mov

### CODE REVIEW

**Review by PromobilityJonatan — APPROVED** [review]

**Review by zilaei — CHANGES_REQUESTED** [review]
Missing schema when opening spm-laiban. Can't run previews.

Getting a bunch of undefined symbol errors when importing package to laiban-ios-example:
Screenshot 2022-11-14 at 08 28 30

**Comment by fredrikhaggbom** [comment]
> Missing schema when opening spm-laiban. Can't run previews.
> 
> Getting a bunch of undefined symbol errors when importing package to laiban-ios-example: Screenshot 2022-11-14 at 08 28 30

Should be resolved with latest commit!

**Comment by zilaei** [comment]
Can't get past parental view.
User input disabled in parental view when running Laiban on hardware iPhone Xr iOS  16.1 and iPad Pro 12.9 (fifth gen) iOS 15.4.1. 

Works fine when testing with simulator.

**Comment by fredrikhaggbom** [comment]
> Can't get past parental view. User input disabled in parental view when running Laiban on hardware iPhone Xr iOS 16.1 and iPad Pro 12.9 (fifth gen) iOS 15.4.1.
> 
> Works fine when testing with simulator.

Hm, strange error. I've tried with two (different kind of) physical devices and can't reproduce it. I will investigate further on monday!

**Comment by zilaei** [comment]
The parental becomes permanently deactivated after a successful login. 
Would It be possible to always keep the parental gate active for views where the user can update values?

**Comment by fredrikhaggbom** [comment]
> The parental becomes permanently deactivated after a successful login. Would It be possible to always keep the parental gate active for views where the user can update values?

The parental gate is now shown every time a new activity will be registered.

**Review by zilaei — APPROVED** [review]
Nice animations! 🦶

**Pull request merged**
